// Centralised UI string catalogue (i18n resource module).
//
// Every user-facing string lives here instead of being scattered inline across
// components. Two locales are provided — Chinese (`zh`, the default) and
// English (`en`) — and `S` is a LIVE module binding that is swapped by
// setLanguage(), so every importer sees the active locale without threading a
// t() prop through the component tree. Values that need runtime data are
// exposed as small formatter functions.

export type Language = 'zh' | 'en';

/** Widen literal types from `as const` so the EN dict can be type-checked
 *  against the exact same key structure as the ZH dict. */
type Widen<T> =
  T extends (...args: never[]) => unknown
    ? T
    : T extends string
      ? string
      : T extends object
        ? { -readonly [K in keyof T]: Widen<T[K]> }
        : T;

const zh = {
  app: {
    name: 'CladeForge',
  },
  menu: {
    new: '新建',
    open: '打开…',
    save: '保存',
    recent: '最近',
    recentEmpty: '（暂无最近文件）',
    recentClear: '清除最近记录',
    importTree: '导入树…',
    exportGroup: '导出',
    fileGroup: '文件',
    helpGroup: '帮助',
    shortcuts: '快捷键速查',
    shortcutsTitle: '快捷键速查 (⌘?)',
    guide: '新手指南',
    guideTitle: '重新查看新手指南（分步讲解画布、面板与命令面板）',
    about: '关于 CladeForge',
    undo: '撤销',
    redo: '重做',
    undoTitle: '撤销 (Cmd/Ctrl+Z)',
    redoTitle: '重做 (Cmd/Ctrl+Shift+Z 或 Ctrl+Y)',
  },
  about: {
    title: '关于 CladeForge',
    version: '版本',
    tagline: '本地交互式系统发育树编辑器',
    author: '作者',
    runtime: '运行环境',
    license: '开源许可',
    close: '关闭',
  },
  lang: {
    label: '语言',
    toggleTitle: '切换中文 / English',
  },
  exportItems: {
    svg: 'SVG（矢量图）',
    png: 'PNG（位图）',
    pdf: 'PDF（矢量图）',
    newick: 'Newick (.nwk)',
    nexus: 'Nexus (.nex)',
    narrative: '叙事报告 (.md)',
    hypothesisJSON: '假说 JSON (.json)',
    rScript: '可重复分析脚本 (.R)',
    reconReport: '协同重建报告 (.md)',
  },
  toolbar: {
    branch: '分支',
    structure: '结构',
    layout: '布局',
    view: '视图',
    context: '上下文',
    contextNode: '节点操作',
    contextEdge: '连线操作',
    contextCanvas: '画布操作',
    contextMulti: '多选操作',
    addBinary: '＋二叉',
    addTernary: '＋三叉',
    addMulti: '＋多叉…',
    addChildren: '添加子节点',
    addSibling: '＋同级',
    insertParent: '插入父节点',
    toggleCollapse: '折叠/展开',
    ladderize: '阶梯化',
    ladderizeAsc: '升序',
    ladderizeDesc: '降序',
    delete: '删除',
    relayout: '重新排布',
    zoomOut: '－',
    zoomIn: '＋',
    fit: '适应窗口',
    clearSelection: '取消选择',
    addBinaryTitle: '为选中节点添加两个子节点',
    addTernaryTitle: '添加三个子节点',
    addMultiTitle: '添加任意数量子节点',
    insertParentTitle: '在选中节点与其父节点之间插入一个节点',
    addSiblingTitle: '为选中节点添加一个同级节点',
    toggleCollapseTitle: '折叠或展开选中节点的子树',
    ladderizeTitle: '按子树大小排列，使树形更紧凑易读',
    searchPlaceholder: '搜索节点…',
    reroot: '定根',
    rerootHere: '以选中节点定根',
    rerootMidpoint: '中点定根',
    deleteTitle: '删除 (Delete)',
    relayoutTitle: '清除手动位置并重新自动排布',
    zoomOutTitle: '缩小',
    zoomInTitle: '放大',
    fitTitle: '适应窗口',
    clearSelectionTitle: '取消选择 (Esc)',
  },
  layoutType: {
    cladogram: '矩形分支图',
    phylogram: '矩形枝长图',
    timeCalibrated: '地质时间图',
    circular: '环形图',
  },
  orientation: {
    LR: '从左到右',
    RL: '从右到左',
    TB: '从上到下',
    BT: '从下到上',
  },
  status: {
    nodes: '节点',
    edges: '连线',
    zoom: '缩放',
    selected: '已选',
    hint: '拖拽移动 · Alt+拖拽改父 · 端口拖拽连线 · 双击重命名 · 滚轮缩放',
    hintButton: '操作提示',
    hintButtonTitle: '查看全部画布手势与快捷键（⌘?）',
    mrcaHint: '已选 2 个节点 · 最近共祖已标橙环',
    saved: '已保存',
    saving: '保存中…',
    // The indicator is driven by the real write result, not by a timer, so a
    // quota-full or blocked localStorage never reads "已保存".
    savedTitle: '自动保存已写入本地存储（重启后可恢复）',
    saveFailed: '自动保存失败',
    saveFailedTitle: '自动保存未写入！最新改动只在内存中，请立即用「文件 › 保存项目」写入磁盘',
    savingTitle: '正在写入本地存储…',
    undoHint: '已撤销',
    redoHint: '已重做',
    undoTitle: (n: number) => `撤销（可撤销 ${n}/100 步）`,
    redoTitle: (n: number) => `重做（可重做 ${n} 步）`,
  },
  theme: {
    label: '主题',
    light: '浅色',
    dark: '深色',
    system: '跟随系统',
    switchToLight: '切换到浅色主题',
    switchToDark: '切换到深色主题',
  },
  gestures: {
    title: '画布操作',
    subtitle: '悬停节点可看到拖拽端口；更多帮助按 ⌘?',
    dragMove: '拖拽节点',
    dragMoveDesc: '移动单个节点（手动位置）',
    altDrag: 'Alt + 拖拽',
    altDragDesc: '把节点拖到另一节点上，改父（重定父）',
    portDrag: '拖拽端口',
    portDragDesc: '从节点右上角的圆点拖出，创建自定义连线',
    dblClick: '双击节点',
    dblClickDesc: '重命名节点',
    wheel: '滚轮 / 空格拖拽',
    wheelDesc: '缩放画布 / 平移画布（中键或按住空格拖拽）',
    shiftSelect: 'Shift + 点击',
    shiftSelectDesc: '多选节点；选 2 个时显示最近共祖',
    arrowNudge: '方向键',
    arrowNudgeDesc: '微调选中节点位置（Shift 为 10px 步进）',
    altArrows: 'Alt + 方向键',
    altArrowsDesc: '在树节点间移动焦点（父/子/兄弟）',
    collapse: '折叠/展开',
    collapseDesc: '工具栏或右键菜单',
    delete: 'Delete / Backspace',
    deleteDesc: '删除所选节点',
  },
  shortcuts: {
    title: '键盘快捷键',
    subtitle: 'CladeForge 快捷键速查',
    global: '全局',
    canvas: '画布',
    palette: '命令面板',
    close: '关闭',
    searchPlaceholder: '搜索快捷键…',
    noResults: '无匹配快捷键',
  },
  legend: {
    title: '图例',
    toggle: '图例',
    toggleTitle: '画布颜色图例',
    mrca: '最近共祖',
    selection: '选中节点',
    dropTarget: '拖放落点',
    connectSource: '连线源点',
    transition: '状态转变（已知 ↔ 已知）',
    needsData: '待补数据（端点未赋值，不计入演化转变）',
    asr: '祖先状态重建饼图',
    event: '演化事件',
    era: '地质年代带',
    stateMarker: '性状状态',
  },
  tour: {
    title: '欢迎使用 CladeForge',
    step1Title: '画布：从这里开始',
    step1Desc: '拖拽节点移动，双击节点重命名，滚轮缩放画布。悬停节点右上角会出现拖拽端口。',
    step2Title: '右侧检视面板',
    step2Desc: '点选画布上的节点或连线后，在此编辑名称、样式、性状状态等单独属性。',
    step3Title: '左侧模块面板',
    step3Desc: '按 展示 / 内容 / 输出 分组的七个模块：样式、性状、假说、协同重建（基因树 DTL）、时间、分析与导出。',
    step4Title: '命令面板（⌘K）',
    step4Desc: '按 ⌘K 可搜索并执行任何操作——重排、定根、分析、导出都在这里。',
    next: '下一步',
    skip: '跳过',
    done: '开始使用',
    dismissedHint: '再次查看请从 帮助 → 新手指南 打开（或按 ⌘K 搜索「新手指南」）。',
  },
  confirm: {
    deleteManyTitle: '确认删除',
    deleteManyMessage: (n: number, tips: number, pct: number) => `将删除 ${n} 个节点（含 ${tips} 个末端节点，占采样 ${pct}%），可撤销。确定继续？`,
    deleteManyConfirm: '删除',
    dontAskAgain: '本次不再提示',
    cancel: '取消',
    rerootTitle: '确认定根',
    rerootMessage: '定根会重排整棵树的拓扑与布局，可能改变手动位置。确定继续？',
    rerootConfirm: '定根',
    rerootHasBranchLength: '当前树有枝长数据，定根后枝长将保留。',
    rerootNoBranchLength: '当前树无枝长数据。',
    rerootAffectsChars: (n: number) => `定根将影响 ${n} 个内部节点的祖先状态标注。`,
    deleteActiveLayerTitle: '确认删除活跃假说层',
    deleteActiveLayerMessage: (current: string, next: string) => `当前假说为「${current}」，删除后将切换到「${next}」。确定继续？`,
    deleteActiveLayerConfirm: '删除',
  },
  importMulti: {
    title: '文件包含多棵树',
    hint: '该文件包含 {n} 棵树，请选择要导入的树（或全部导入为多个标签页）。',
    tips: '末端',
    depth: '深度',
    importSelected: '导入所选',
    importAll: '全部导入',
    cancel: '取消',
    consensus: '构建共识树',
    consensusMethod: '共识方法',
    strict: '严格共识',
    majorityRule: '50% 多数规则',
  },
  nav: {
    groupContent: '内容',
    groupView: '展示',
    groupOut: '输出',
    traits: '性状',
    traitsHint: '性状定义与颜色映射',
    layers: '假说',
    layersHint: '竞争假说层管理',
    recon: '协同',
    reconHint: '基因树 / 物种树 DTL 协同重建',
    time: '时间',
    timeHint: '时间校准与环境背景事件',
    style: '样式',
    styleHint: '布局与全局样式',
    analysis: '分析',
    analysisHint: '推理与分析',
    export: '导出',
    exportHint: '导出文件',
  },
  recon: {
    section: '协同重建 (DTL)',
    geneTrees: '基因树',
    importFile: '从文件导入基因树',
    importTab: '从打开的标签页导入',
    rename: '重命名',
    remove: '移除基因树',
    empty: '尚未导入基因树。导入后可将其尖端按名称匹配到当前物种树，进行 DTL 协同重建。',
    activeGene: '当前基因树',
    mappedCount: '已解析内部节点',
    cntSpeciation: '物种化 σ',
    cntDuplication: '加倍 δ',
    cntTransfer: '转移 τ',
    cntLosses: '损失 λ',
    validation: '一致性校验',
    noIssues: '无不一致',
    issuesTitle: '问题列表（点击定位）',
    suggestLca: '按 LCA 生成建议',
    clearAssumptions: '清空假设',
    costs: '代价设置 (δ / τ / λ)',
    costDup: '加倍 δ',
    costTransfer: '转移 τ',
    costLoss: '损失 λ',
    dpRun: '计算最优解 (DP)',
    dpApply: '将最优解应用为假设',
    dpCurrent: '当前假设总代价',
    dpOptimal: 'DP 最优总代价',
    // The absolute event / loss totals of this DP are not comparable with
    // RAINIEFF / RaGTeP / Treerecon output — the panel must say so wherever a
    // number is quoted.
    dpComparability: '口径声明：本模块的代价是最小代价简约解（非似然），且三处刻意选择使绝对事件/损失数系统性低于 RAINIEFF / RaGTeP / Treerecon：基因树根可自由放置而不付"家族到达"代价（可在下方显式计价）、经过物种节点汇合处但未进入姐妹枝的谱系不按汇合处计价、未受约束的物种枝不计推测丢失。请把数字引用为"本模型下的事件数"，不要与其他软件的计数互换。',
    dpInvariant: '同一份场景用同一套代价重算，故"当前"与"最优"可比较；两者相等即当前假设已是该代价向量下的最优解。',
    dpFreeRoot: (cost: number) => `基因根被放置在物种树内部（自由根）：本次代价未含家族到达费用（rootTransferCost = ${cost}）。`,
    dpAmbiguousNodes: (n: number) => `${n} 个基因节点存在代价完全相同的其他事件类型（经典的加倍/物种化不可辨识，以及转移方向镜像）：界面按 加倍 > 物种化 > 转移 的既定优先级显示其中一种，并非唯一解。`,
    dpAmbiguousLabels: (n: number) => `${n} 个尖端标签在归一化（去空格/大小写不敏感）后互相冲突，已按未匹配处理，不参与协同。`,
    lossSplit: (internal: number, tips: number) => `损失 λ = 内部枝 ${internal} + 尖端入枝 ${tips}（尖端枝上的丢失现已计入）`,
    costsRejected: '代价设置被部分拒绝',
    dpNoBinary: '需要二叉基因树才能求解',
    severityError: '错误',
    severityWarning: '提示',
    enterView: '进入协同视图',
    exitView: '返回标准视图',
    viewStandard: '标准视图',
    viewRecon: '协同视图',
  },
  reconInspector: {
    title: 'DTL 假设',
    mapTo: '映射到物种节点',
    event: '事件类型',
    evSpeciation: '物种化 σ',
    evDuplication: '加倍 δ',
    evTransfer: '转移 τ',
    evClear: '清除事件',
    losses: '损失数 (入支)',
    emptyHint: '在右侧基因窗格单击节点以查看/编辑其 DTL 假设；Alt+单击左窗格物种节点可快速设定所选基因节点的映射。',
    tipHint: '尖端只设定映射，不携带事件。',
    geneTreeSection: '基因树信息',
    tipCount: '尖端数',
  },
  exportGroup: {
    vector: '矢量图',
    raster: '位图',
    data: '数据文件',
    report: '报告',
  },
  nexusExport: {
    title: 'NEXUS 导出选项',
    includeCharacters: '包含性状矩阵 (CHARACTERS block)',
    includeHypothesis: '包含假说层 (ASSUMPTIONS block)',
    includeMrBayes: '生成 MrBayes block',
    includeBeast: '生成 BEAST block',
    confirm: '导出',
    cancel: '取消',
  },
  inspector: {
    empty: '未选择对象',
    emptyHint: '在画布中点选一个节点或连线，即可在此编辑其单独属性。整体样式请使用左侧「整体布局」面板。',
    searchPlaceholder: '搜索属性…',
    noResults: '无匹配属性',
    noResultsHint: '未找到相关属性。全局默认样式请在左侧「样式」模块的「整体布局」中查找。',
    advanced: '高级选项',
    inherited: '继承全局默认',
    overridden: '已覆盖全局默认',
    restoreDefault: '恢复默认',
    restoreDefaultTitle: '清除此对象的所有样式覆盖，恢复为全局默认',
  },
  tabs: {
    newTab: '新建标签页',
    close: '关闭标签页',
    untitled: '未命名',
    closeConfirmTitle: '关闭标签页？',
    closeConfirmMessage: (name: string) => `标签页「${name}」有未保存的更改，关闭后无法恢复。确定关闭吗？`,
  },
  cmd: {
    placeholder: '输入命令或英文别名…',
    none: '无匹配命令',
    newTab: '新建标签页',
    open: '打开项目…',
    save: '保存项目',
    importTree: '导入树…',
    exportSvg: '导出 SVG',
    exportPng: '导出 PNG',
    exportPdf: '导出 PDF',
    exportNewick: '导出 Newick',
    exportNexus: '导出 Nexus',
    exportNarrative: '导出叙事报告',
    exportHypothesis: '导出假说 JSON',
    undo: '撤销',
    redo: '重做',
    fit: '适应窗口',
    relayout: '重新排布',
    ladderizeAsc: '阶梯化（升序）',
    ladderizeDesc: '阶梯化（降序）',
    rerootHere: '以选中节点定根',
    rerootMidpoint: '中点定根',
    rerootOutgroup: '以选中的类群为外群定根',
    rerootOutgroupCount: (n: number) => `以外群定根（已选 ${n} 个节点）`,
    addBinary: '添加二分分支',
    toggleCollapse: '折叠/展开选中节点',
    runAsr: 'Mk 概率重建',
    matrix: '打开性状矩阵',
    analysis: '推理辅助',
    search: '搜索节点',
    guide: '新手指南',
    extractSubtree: '提取子树为新标签页',
  },
  addDialog: {
    title: '添加多叉分支',
    countLabel: '子节点数量',
    polytomyType: '多分叉类型',
    hardPolytomy: '硬多分叉（同时分化）',
    softPolytomy: '软多分叉（未解决）',
    cancel: '取消',
    confirm: '添加',
  },
  context: {
    deleteEdge: '删除连线',
    addBinary: '添加二叉分支',
    addTernary: '添加三叉分支',
    addMulti: '添加多叉分支…',
    addSibling: '添加同级节点',
    insertParent: '插入父节点',
    reroot: '以此节点定根',
    outgroupReroot: '设为外群并定根',
    // The item must be reachable from a single selected node too, and its
    // label has to say how many nodes form the outgroup.
    outgroupRerootCount: (n: number) => `以所选 ${n} 个节点为外群定根`,
    expandSubtree: '展开子树',
    collapseSubtree: '折叠子树',
    resetPosition: '重置位置',
    deleteNode: '删除节点',
    fit: '适应窗口',
  },
  dash: {
    solid: '实线',
    dashed: '虚线',
    dotted: '点线',
  },
  branchShape: {
    label: '分支形状',
    line: '细线',
    rectangular: '粗矩形',
    rounded: '圆头粗线',
  },
  node: {
    section: '节点',
    name: '名称',
    branchLength: '枝长',
    support: '支持率',
    age: '年代',
    timeConstraintSection: '时间约束',
    calibrationMin: '最小年代',
    calibrationMax: '最大年代',
    noCalibration: '此节点暂无时间校准。',
    addCalibration: '添加校准',
    styleSection: '节点样式',
    shape: '形状',
    shapeCircle: '圆形',
    shapeSquare: '方形',
    shapeDiamond: '菱形',
    shapeNone: '无',
    size: '大小',
    fill: '填充色',
    stroke: '描边色',
    strokeWidth: '描边宽度',
    labelSection: '标签',
    showLabel: '显示标签',
    labelColor: '标签颜色',
    fontSize: '字号',
    fontWeight: '字重',
    rotation: '旋转角度',
    italic: '斜体',
    bold: '加粗',
    labelPosition: '标签位置',
    labelOffsetX: '标签 X 偏移',
    labelOffsetY: '标签 Y 偏移',
    branchSection: '入边分支样式',
    branchShape: '分支形状',
    color: '颜色',
    width: '线宽',
    dash: '线型',
    expand: '展开',
    collapse: '折叠',
    resetPosition: '重置位置',
    delete: '删除',
    portTitle: '拖拽到另一个节点以创建自定义连线',
  },
  edge: {
    section: '自定义连线',
    label: '标签',
    color: '颜色',
    width: '线宽',
    dash: '线型',
    arrow: '箭头',
    curvature: '弯曲度',
    delete: '删除连线',
  },
  multi: {
    section: '多选',
    applyToAll: '批量应用到所选',
    fill: '填充色',
    stroke: '描边色',
    nodeSize: '节点大小',
    labelColor: '标签颜色',
    fontSize: '字号',
    branchColor: '分支颜色',
    showLabel: '显示标签',
    hideLabel: '隐藏标签',
    deleteSelected: '删除所选',
  },
  doc: {
    layoutSection: '布局与画布',
    hGap: '层级间距',
    vGap: '同级间距',
    background: '画布背景',
    defaultsSection: '默认样式',
    defaultBranchColor: '默认分支色',
    defaultEdgeColor: '默认连线色',
    hintSection: '操作提示',
  },
  fontWeightOpts: {
    light: '细体 (300)',
    normal: '常规 (400)',
    medium: '中等 (500)',
    semibold: '半粗 (600)',
    bold: '加粗 (700)',
    black: '特粗 (900)',
  },
  layoutPanel: {
    title: '整体布局',
    presetSection: '样式预设',
    layoutSection: '树形布局',
    type: '树形',
    orientation: '方向',
    spacingSection: '间距',
    branchGap: '分支间距',
    levelGap: '层级间距',
    branchSection: '分支样式',
    branchShape: '分支形状',
    branchWidth: '分支粗细',
    branchColor: '分支颜色',
    gradientSection: '颜色渐变',
    gradientEnable: '启用渐变',
    gradientFrom: '根部颜色',
    gradientTo: '末端颜色',
    gradientHint: '根→末端渐变着色（未单独设色的分支）。',
    fontSection: '字体与标签',
    fontSize: '字体大小',
    fontWeight: '字重（粗细）',
    rotation: '旋转角度',
    italic: '倾斜（斜体）',
    bold: '加粗',
    showLabel: '显示标签',
    labelColor: '标签颜色',
    canvasSection: '画布',
    background: '画布背景',
    edgeSection: '默认连线',
    edgeColor: '连线颜色',
    timeSection: '时间轴',
    timeUnit: '时间单位',
    // The unit is a closed list, not free text: the ICS era bands and the axis
    // are hard-wired to Ma, so a value like "ka" would shift the whole colour
    // band by 10³ without complaint. Anything but Ma turns the geological
    // overlay off instead of lying.
    timeUnitMa: 'Ma（百万年，地质色带所用单位）',
    timeUnitKa: 'ka（千年）',
    timeUnitGa: 'Ga（十亿年）',
    timeUnitMyr: 'Myr（百万年，等同 Ma）',
    timeUnitYr: 'yr（年）',
    timeUnitOther: '其他/自定义',
    timeUnitHint: (unit: string) => `数值本身不做换算：节点年代与事件区间仍按你填写的数字解释，标签只写为「${unit}」。若需要换算请在导入前自行换算。`,
    timeUnitBlocksEras: (unit: string) => `地质代/纪色带按 Ma 定义（timescale.ts 的 ICS 边界），当前单位「${unit}」不是 Ma ⇒ 色带已停用，以免整体错位 10³ 倍。`,
    showEras: '显示地质年代',
    circularIgnoresAges: '环形布局只按拓扑层数排半径，不读取节点年代：切到环形后年代轴、代/纪色带与环境事件带都不再显示（数据未被破坏，只是不消费）。',
    phylogramMissingLengths: (n: number, total: number) => `${n}/${total} 条枝没有可用枝长，已按 0 长度画在原层深位置并以灰色虚线标记：这些枝的横向距离没有含义，比例尺只描述有长度的那些枝。`,
    branchLengthUnknownLegend: '灰色虚线枝＝未记录枝长（非零长度）',
    estimateAges: '按拓扑估算年代',
    agesEstimated: '已按拓扑估算年代，可在时间轴中逐个微调',
    agesAreEstimated: '本树的部分年代是按拓扑估算的（非化石/校准证据），请逐项核对后再用于分析或投稿。',
    timeHint: '地质时间图：按手填年代排列节点，可在右侧逐个设置。',
    timeNotCalibrated: '当前为纯拓扑树，无时间数据。时间轴与环境事件不可用。',
    timeNotCalibratedHint: '请先设置节点年代或添加校准点，或点击「按拓扑估算年代」生成相对时间。',
    timeCalibrated: '已检测到时间数据，时间轴功能可用。',
    // Shown when the tree has time data but the layout is not time-calibrated.
    timeDataButWrongLayout: (layoutName: string) => `时间数据已具备，但当前布局为「${layoutName}」，切换到「地质时间图」后显示时间轴与环境事件。`,
    // One-click switch offered by the Time panel when the layout is not the
    // geological time chart yet (mirrors the 样式 module's 树形 selector).
    switchToTimeChart: '切换到地质时间图',
    // Geological-era display level: eons (宙), periods (纪) or both.
    eraLevelLabel: '显示级别',
    eraLevelEon: '仅显示宙',
    eraLevelPeriod: '仅显示纪',
    eraLevelBoth: '宙、纪都显示',
    // Shown when time-calibrated layout is active but some nodes lack ages.
    missingAgesWarning: (n: number) => `${n} 个节点未设年代，将按现今（0）处理`,
    missingAgesListPrefix: '缺年代节点：',
    missingAgesMore: (n: number) => `等 ${n} 个`,
    // Clarification that calibration points don't affect the layout.
    calibrationHint: '校准点当前仅随 NEXUS 导出，不会自动推算节点年代。',
    envSection: '环境事件',
    envAdd: '＋添加环境事件',
    envFrom: '起',
    envTo: '止',
    envEmpty: '暂无环境事件（气候/大陆漂移/大灭绝等）。',
    applyHint: '全局设置；单个对象可在右侧面板覆盖。',
    calibrationSection: '校准点',
    calibrationAdd: '＋添加校准点',
    calibrationNode: '节点',
    calibrationMin: '最小年代',
    calibrationMax: '最大年代',
    calibrationEmpty: '暂无校准点。请添加至少一个校准点以进行时间校准。',
    supportSection: '支持率阈值',
    supportThreshold: '支持率阈值（0–100）',
    // The control drives both the canvas and the exported figure, and a stored
    // 0–1 posterior is normalised to a percentage before the comparison, so a
    // Bayesian tree is not entirely "faded out".
    supportThresholdHint: '低于此阈值的分支在画布与导出图中淡显（虚线 + 变浅）。支持率按 0–100 比较；0–1 的后验概率会先换算成百分比再判断。',
    supportThresholdNoData: '本树没有任何支持率数据，设置阈值不会改变外观。',
  },
  character: {
    section: '性状与状态',
    colorBy: '着色依据',
    colorByNone: '无（按节点样式）',
    showTransitions: '显示状态转变',
    list: '性状列表',
    empty: '暂无性状，点击下方新建。',
    add: '新建性状',
    openMatrix: '性状矩阵…',
    analysisMenu: '分析 ▾',
    edit: '编辑',
    name: '名称',
    type: '类型',
    typeDiscrete: '离散',
    typeContinuous: '连续',
    states: '状态',
    addState: '＋添加状态',
    stateLabel: '状态名',
    lowColor: '低值色',
    highColor: '高值色',
    deleteCharacter: '删除性状',
    stepMatrix: '代价矩阵 (Sankoff)',
    stepMatrixHint: '行→列为“从→到”的转变代价；影响简约法建议与一致性检查。',
    resetWeights: '重置为等权',
    analysis: '推理辅助…',
    asr: '祖先重建',
    runAsr: 'Mk 概率重建',
    clearAsr: '清除',
    asrHint: '基于等速率 Mk 模型计算每个内部节点的状态概率分布（饼图）。',
    done: '完成',
  },
  matrix: {
    title: '性状矩阵',
    taxon: '分类单元（tip）',
    close: '关闭',
    unassigned: '—',
    empty: '先在左侧面板新建至少一个性状。',
    hint: '只列出叶节点（已知状态）；内部节点的“祖先状态假说”请在画布上点选节点后在右侧设置。',
  },
  nodeChar: {
    section: '性状状态',
    tipHint: '叶节点：已知观测状态。',
    internalHint: '内部节点：你对祖先状态的"假说"。',
    unassigned: '（未设置）',
    missing: '缺失（?）',
    notApplicable: '不适用（-）',
    valuePlaceholder: '数值',
    noCharacters: '尚未定义性状；请先在左侧「性状与状态」中新建。',
    evidence: '证据',
    suggest: '简约法建议',
    accept: '采纳',
    ambiguous: '存在多个等价最优解',
  },
  event: {
    section: '演化事件',
    showEvents: '显示事件',
    add: '＋添加事件',
    type: '类型',
    target: '位置',
    targetNode: '节点',
    targetBranch: '分支（入边）',
    label: '标题',
    labelPlaceholder: '（默认用类型名）',
    note: '描述',
    triggers: '触发（因果链）',
    triggersNone: '暂无其他事件可关联',
    delete: '删除事件',
    empty: '此节点/分支暂无事件。',
  },
  confidence: {
    label: '置信度',
    none: '（未评）',
    high: '高',
    medium: '中',
    low: '低',
    support: '支持证据',
    against: '反对证据',
  },
  analysis: {
    title: '推理辅助',
    character: '性状',
    parsimonySection: '简约法（祖先状态建议）',
    cost: '最小代价 / 变化次数',
    fill: '生成简约法建议',
    fillHint: '系统为每个内部节点生成建议状态（非覆盖），你可在右侧面板逐个采纳。',
    signalSection: '系统发育信号（CI/RI）',
    steps: '变化次数 s',
    minSteps: '最小步数 m',
    maxSteps: '最大步数 g',
    signalHint: 'CI = m/s，RI = (g−s)/(g−m)。越接近 1，性状与拓扑越一致；偏低提示同塑（趋同/平行演化），值得作为假说探究。两者只在等价代价（无 Sankoff 步矩阵）下有定义。',
    signalNone: '需要 ≥3 个已赋值末端与 ≥2 个状态。',
    signalWeighted: '本性状带有 Sankoff 步矩阵：CI/RI 以"步数"为分子分母（m = 状态数 −1、g = 尖端数 − 众数频数），在加权代价下失去意义，故不予报告。',
    signalMissingCodes: (n: number) => `${n} 个尖端的取值是缺失符号（? / -）或已删除的状态，未计入 m、g、s。`,
    consistencySection: '一致性检查',
    consistencyNone: '未发现明显问题。',
    consistencyAmbiguous: '模糊重建',
    consistencyHomoplasy: '同塑',
    consistencyMissing: '缺失数据影响',
    consistencyMismatch: '局部不一致',
    consistencyExcess: '过多变化',
    correlationSection: '性状相关性',
    // The metric is the Jaccard overlap of the two characters' MP change-branch
    // sets, not a Phi coefficient. The overlap is descriptive; significance only
    // appears after the tree-constrained permutation test has actually been run.
    correlationNone: '未发现 Jaccard 重叠比 ≥ 0.5 的性状对（需至少两个离散性状，各自 ≥2 条变化枝）。',
    correlationType: 'Jaccard 重叠比',
    correlationSample: (n: number) => `n = ${n}`,
    correlationShared: (shared: number, a: number, b: number) => `共享变化枝 ${shared}（A ${a} 枝 / B ${b} 枝）`,
    correlationExpected: (v: number) => `独立期望 ≈ ${v.toFixed(2)} 枝（|A|·|B|/|N|，N 为全部分枝数）`,
    correlationDescriptive: '重叠比只是描述性指标：高重叠提示值得深究的共变，不等于显著，也不等于因果。',
    correlationRunTest: '运行树约束置换检验',
    correlationRerunTest: '重新运行置换检验',
    correlationTesting: '置换检验运行中…',
    correlationTestHint: '置换检验会打乱 B 性状在已赋值尖端上的状态分布（保持边缘频数与缺失模式），在同一拓扑与同一简约步矩阵下重算其变化枝集，统计量为同样的 Jaccard 重叠比；p = (1 + 超过观测值的置换数)/(置换数 + 1)。',
    correlationTestMethod: (method: string) => `检验方法：${method}`,
    correlationPValue: '原始置换 p',
    correlationPSummary: (p: number, perms: number, resolution: number) =>
      `p ${p <= resolution ? '<' : '='} ${p <= resolution ? resolution.toFixed(4) : p.toFixed(4)}（${perms} 次置换）`,
    correlationNullMean: (v: number) => `置换零分布均值 ${v.toFixed(3)}`,
    correlationSignificant: (n: number) =>
      `${n} 对在 Holm–Bonferroni 校正后（α = 0.05）判为显著`,
    correlationNoSignificance: '未运行检验 ⇒ 只显示重叠比，不给出任何"显著/不显著"判断。',
    correlationMultiTest: (pairs: number) =>
      `本族共 ${pairs} 个 p 值，已按 Holm–Bonferroni 逐步降序校正；判"显著"只看校正后的值（族内 1 个以上比较时，未校正的 p 不能直接当 0.05 判据）`,
    // Multiplicity control, and the inference is kept separate from the
    // descriptive ≥0.5 gate, so the UI has to name both.
    correlationPAdjusted: 'Holm–Bonferroni 校正后 p',
    correlationVerdictYes: '校正后显著（≤ 0.05）',
    correlationVerdictNo: '校正后不显著（> 0.05）',
    correlationAllTestedTitle: '本族全部检验结果（含未达 0.5 描述性门槛的性状对）',
    correlationSkippedPairs: (n: number) =>
      `另有 ${n} 对因置换检验开销上限未纳入本族（不做校正，也不给结论）`,
    correlationGateNote:
      '凡两端变化枝数 ≥2 的性状对都会进入检验族，族内所有 p 值一并校正后再判显著',
    correlationNotTestable: (why: string) => `该对无法检验（${why}）：只保留描述性重叠比`,
    correlationNotTestableWhy: '可测置换次数不足（树过大或已赋值尖端少于 3 个）',
    close: '关闭',
    needCharacter: '先在左侧新建并选择一个离散性状。',
    treeSummarySection: '树摘要统计',
    tipCount: '末端节点数',
    internalCount: '内部节点数',
    resolution: '分辨率（二叉率）',
    avgBranchLength: '平均枝长',
    totalBranchLength: '总枝长',
    treeHeight: '树高 (root-to-tip)',
    treeHeightUnitBranch: '单位：枝长（树内已记录枝长）',
    treeHeightUnitEdges: '单位：边数（无任何枝长，按拓扑层数计）',
    sackinIndex: 'Sackin 索引',
    collessIndex: 'Colless 索引',
    // Colless is defined for rooted BINARY trees; what the code emits for
    // a tree with polytomies is the max−min variant, un-normalised.
    collessBinaryOnly: (n: number) => `本树有 ${n} 个非二叉内部节点：此处为 max−min 多歧推广变体，未做 n 归一化，不能与二叉树的 Colless 值直接比较。`,
    branchLengthCoverage: (have: number, missing: number) => `${have} 条枝记录有长度、${missing} 条没有；未记录与非有限值按 0 计入总枝长，0（同期分化）是真实数据。`,
    continuousSection: '连续性状分析',
    blombergK: 'Blomberg\'s K',
    // K is a point estimate here. Without the trait-shuffling / BM-simulation
    // test it licenses no evolutionary verdict, so the wording is a reading aid
    // and never "保守演化" / "过度分散".
    blombergKHint: 'K 是相对布朗运动（BM = 1）的点估计：K > 1 意味着比 BM 更聚集，K < 1 意味着更分散。本程序不运行置换或模拟检验，因此界面不据此下演化结论。',
    blombergKNoTest: '无显著性检验：K 与 1 的差可能整个落在随机变异之内，需以性状置换或 BM 模拟检验后才能判读。',
    blombergKScale: (imputed: number, total: number) =>
      imputed === 0
        ? `枝长覆盖：${total}/${total} 条枝使用所填长度`
        : `枝长覆盖：仅 ${total - imputed}/${total} 条枝有长度，其余按 1 代入 ⇒ 实为"拓扑（分支图）尺度"的 K，而非年代尺度`,
    continuousNone: '需要至少一个有赋值的连续性状。',
    continuousBlockedReason: (why: string) => `未给出 K：${why}`,
    asrModelSection: 'ASR 模型设置',
    asrModel: '速率模型',
    asrModelER: 'ER（等速率）',
    asrThreshold: '仅显示概率 > 阈值的状态',
    asrThresholdHint: (t: number) =>
      `饼图中后验 < ${t.toFixed(2)} 的态不再绘制；当某一态的后验 ≥ ${(1 - t).toFixed(2)}（其余态必然全部落在阈值之下）时整盘按该态填实色。该阈值由渲染层读取，仅影响显示，不参与似然计算。`,
    asrRun: '运行 ASR',
    asrResultSummary: '结果摘要',
    asrNoWarnings: '无降级告警',
    asrWarningCount: (n: number) => `${n} 类降级告警`,
    asrWarningList: (kind: string, n: number) => `${kind}：${n} 个节点`,
    // The four degradation classes are distinct statements — an unset
    // length is not a recorded zero.
    asrWarnUnset: '未设置枝长（按 1 代入）',
    asrWarnZero: '枝长为 0（同期分化，按 0 参与计算）',
    asrWarnNegative: '负枝长（无效，按 1 代入）',
    asrWarnInvalid: '非有限枝长 NaN/∞（无效，按 1 代入）',
    asrWarnCollapse: '后验崩塌（全为 −∞，退回均匀分布）',
    asrModelErOnly: '当前仅实现 ER（等速率）Mk：闭式转移概率只对 ER 成立，SYM/ARD 不提供选项。',
  },
  layer: {
    section: '假说层',
    current: '当前假说',
    name: '名称',
    addBlank: '新建',
    duplicate: '复制',
    remove: '删除',
    copySuffix: '副本',
    hint: '多套假说独立保存，叶节点观测共享。',
  },
  characterExtra: {
    symmetric: '对称模式',
    symmetricHint: '勾选后只需编辑上三角，下三角自动镜像。',
    missingData: '缺失（?）',
    notApplicable: '不适用（-）',
    // A cell that still holds a value which is not a declared state of this
    // character: shown read-only so nothing is silently rewritten.
    staleValue: (id: string) => `残留值 ${id}（非本性状状态）`,
  },
  group: {
    hypothesisData: '假说与数据',
    layoutStyle: '布局与样式',
  },
  analysisMenu: {
    label: '分析',
    matrix: '性状矩阵…',
    inference: '推理辅助…',
    asr: 'Mk 概率重建',
    clearAsr: '清除重建',
  },
  canvasControls: {
    zoomIn: '＋',
    zoomOut: '－',
    actualSize: '1:1',
    fit: '适应',
    relayout: '整理',
    zoomInTitle: '放大',
    zoomOutTitle: '缩小',
    actualSizeTitle: '实际大小 (100%)',
    fitTitle: '适应窗口',
    // fitView clamps at MIN_SCALE, so "fit" silently fails to show the
    // whole tree on very tall layouts; the zoom readout says so.
    fitClampedTitle: '已触及缩放下限 10%：整棵树仍放不下，请增大层级/分支间距或折叠部分子树',
    fitClamped: '已达最小缩放',
    relayoutTitle: '清除手动位置并按固定间距重新排布',
  },
  panel: {
    resizeTitle: '拖拽调整面板宽度',
    closeOverlay: '关闭面板',
  },
  section: {
    pin: '固定展开',
    unpin: '取消固定（可折叠）',
    items: '项',
    unfavorite: '取消收藏',
    favorite: '收藏',
  },
  busy: {
    exportPdf: '正在导出 PDF…',
    exportPng: '正在导出 PNG…',
    exportSvg: '正在导出 SVG…',
  },
empty: {
title: '开始构建你的系统发育树',
hint: '拖入 .nwk / .nex / .tree 文件，或按 ⌘O / Ctrl+O 导入；也可用上方工具栏的「＋二叉」直接开始搭建。',
loadSample: '载入示例树',
loadSampleTitle: '加载一棵带性状与演化事件的示例树，快速体验各项功能',
samplePickerTitle: '选择一个示例项目',
samplePickerHint: '涵盖古菌、细菌、病毒及动植物的演化案例，均含性状与演化事件',
},
  notify: {
    openProjectFail: '打开项目失败',
    saveProjectFail: '保存项目失败',
    importFail: '导入树失败',
    exportNewickFail: '导出 Newick 失败',
    exportNexusFail: '导出 Nexus 失败',
    exportSvgFail: '导出 SVG 失败',
    exportPngFail: '导出 PNG 失败',
    exportPdfFail: '导出 PDF 失败',
    exportNarrativeFail: '导出叙事报告失败',
    exportHypothesisFail: '导出假说 JSON 失败',
    projectSaved: '项目已保存',
    projectOpened: '项目已打开',
    treeImported: '树已导入',
    exported: '已导出',
    saveCancelled: '已取消保存',
    undo: '撤销',
    addRootFallback: '未选中节点，将向根节点添加',
    noBranchLength: '当前树无枝长数据，显示效果与分支图相同',
    needBranchLength: '需要枝长数据才能进行中点定根',
    needCalibration: '请添加至少一个校准点',
    consensusBuilt: '共识树已构建',
    consensusFail: '无法构建共识树',
    // The reason comes from `buildConsensusTree`'s issue sink, so a failed
    // consensus is never an unexplained "构建失败".
    consensusIssues: (reason: string) => `无法构建共识树：${reason}`,
    consensusPartial: (reason: string) => `共识树已构建，但有保留项：${reason}`,
    // Outgroup rooting needs a selection, and can legitimately be a no-op.
    outgroupNeedsSelection: '请先选中作为外群的节点（Shift+点击可多选）',
    outgroupNoOp: '外群无法重根：所选节点已是根、或直接挂在当前根之下（此时该分类单元已位于基部分支）',
    outgroupDone: (n: number) => `已以外群重根（外群 ${n} 个节点，选择已保留）`,
    // The cost writer rejects unusable values; the panel says so.
    costsRejected: (why: string) => `代价未完全生效：${why}`,
    timeNotCalibrated: '当前树无时间数据。请先设置节点年代或添加校准点，或点击「按拓扑估算年代」生成相对时间。',
    timeDataInconsistent: (n: number) => `发现 ${n} 处时间数据不一致，请检查节点年代或校准点`,
    // Toast shown when switching to time-calibrated layout with nodes missing ages.
    missingAgesToast: (n: number) => `${n} 个节点未设年代，将按现今（0）处理`,
  },
} as const;

export type Strings = Widen<typeof zh>;

const en: Strings = {
  app: {
    name: 'CladeForge',
  },
  menu: {
    new: 'New',
    open: 'Open…',
    save: 'Save',
    recent: 'Recent',
    recentEmpty: '(no recent files)',
    recentClear: 'Clear Recent',
    importTree: 'Import Tree…',
    exportGroup: 'Export',
    fileGroup: 'File',
    helpGroup: 'Help',
    shortcuts: 'Keyboard Shortcuts',
    shortcutsTitle: 'Keyboard Shortcuts (⌘?)',
    guide: 'Beginner Tour',
    guideTitle: 'Replay the guided tour (canvas, panels, command palette)',
    about: 'About CladeForge',
    undo: 'Undo',
    redo: 'Redo',
    undoTitle: 'Undo (Cmd/Ctrl+Z)',
    redoTitle: 'Redo (Cmd/Ctrl+Shift+Z or Ctrl+Y)',
  },
  about: {
    title: 'About CladeForge',
    version: 'Version',
    tagline: 'Local interactive phylogenetic tree editor',
    author: 'Author',
    runtime: 'Runtime',
    license: 'Licence',
    close: 'Close',
  },
  lang: {
    label: 'Language',
    toggleTitle: 'Switch 中文 / English',
  },
  exportItems: {
    svg: 'SVG (vector)',
    png: 'PNG (raster)',
    pdf: 'PDF (vector)',
    newick: 'Newick (.nwk)',
    nexus: 'Nexus (.nex)',
    narrative: 'Narrative report (.md)',
    hypothesisJSON: 'Hypothesis JSON (.json)',
    rScript: 'Reproducible R script (.R)',
    reconReport: 'Reconciliation report (.md)',
  },
  toolbar: {
    branch: 'Branch',
    structure: 'Structure',
    layout: 'Layout',
    view: 'View',
    context: 'Context',
    contextNode: 'Node actions',
    contextEdge: 'Edge actions',
    contextCanvas: 'Canvas actions',
    contextMulti: 'Multi-select actions',
    addBinary: '+ Binary',
    addTernary: '+ Ternary',
    addMulti: '+ Polytomy…',
    addChildren: 'Add children',
    addSibling: '+ Sibling',
    insertParent: 'Insert parent',
    toggleCollapse: 'Collapse/Expand',
    ladderize: 'Ladderize',
    ladderizeAsc: 'Ascending',
    ladderizeDesc: 'Descending',
    delete: 'Delete',
    relayout: 'Re-layout',
    zoomOut: '－',
    zoomIn: '＋',
    fit: 'Fit to window',
    clearSelection: 'Clear selection',
    addBinaryTitle: 'Add two child nodes to the selected node',
    addTernaryTitle: 'Add three child nodes',
    addMultiTitle: 'Add any number of child nodes',
    insertParentTitle: 'Insert a node between the selection and its parent',
    addSiblingTitle: 'Add a sibling next to the selected node',
    toggleCollapseTitle: 'Collapse or expand the selected subtree',
    ladderizeTitle: 'Sort by subtree size for a more compact tree',
    searchPlaceholder: 'Search nodes…',
    reroot: 'Reroot',
    rerootHere: 'Reroot at selected node',
    rerootMidpoint: 'Midpoint reroot',
    deleteTitle: 'Delete (Delete)',
    relayoutTitle: 'Clear manual positions and re-run auto layout',
    zoomOutTitle: 'Zoom out',
    zoomInTitle: 'Zoom in',
    fitTitle: 'Fit to window',
    clearSelectionTitle: 'Clear selection (Esc)',
  },
  layoutType: {
    cladogram: 'Rectangular cladogram',
    phylogram: 'Rectangular phylogram',
    timeCalibrated: 'Geological time chart',
    circular: 'Circular',
  },
  orientation: {
    LR: 'Left to right',
    RL: 'Right to left',
    TB: 'Top to bottom',
    BT: 'Bottom to top',
  },
  status: {
    nodes: 'Nodes',
    edges: 'Edges',
    zoom: 'Zoom',
    selected: 'Selected',
    hint: 'Drag to move · Alt+drag to reparent · drag port to link · double-click to rename · wheel to zoom',
    hintButton: 'Gestures',
    hintButtonTitle: 'See all canvas gestures and shortcuts (⌘?)',
    mrcaHint: '2 nodes selected · MRCA ring highlighted',
    saved: 'Saved',
    saving: 'Saving…',
    // The indicator is driven by the real write result, not by a timer, so a
    // quota-full or blocked localStorage never reads "Saved".
    savedTitle: 'Autosave written to local storage (restored on restart)',
    saveFailed: 'Autosave failed',
    saveFailedTitle: 'Autosave did NOT write. The latest edits exist only in memory — use File › Save project now',
    savingTitle: 'Writing to local storage…',
    undoHint: 'Undone',
    redoHint: 'Redone',
    undoTitle: (n: number) => `Undo (${n}/100 steps available)`,
    redoTitle: (n: number) => `Redo (${n} steps available)`,
  },
  theme: {
    label: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    switchToLight: 'Switch to light theme',
    switchToDark: 'Switch to dark theme',
  },
  gestures: {
    title: 'Canvas gestures',
    subtitle: 'Hover a node to see its link port; press ⌘? for more help',
    dragMove: 'Drag node',
    dragMoveDesc: 'Move a single node (manual position)',
    altDrag: 'Alt + drag',
    altDragDesc: 'Drop onto another node to reparent it',
    portDrag: 'Drag port',
    portDragDesc: 'Drag from the dot at a node’s top-right to create a custom link',
    dblClick: 'Double-click node',
    dblClickDesc: 'Rename the node',
    wheel: 'Wheel / Space+drag',
    wheelDesc: 'Zoom the canvas / pan (middle button or Space+drag)',
    shiftSelect: 'Shift + click',
    shiftSelectDesc: 'Multi-select; with 2 selected the MRCA is shown',
    arrowNudge: 'Arrow keys',
    arrowNudgeDesc: 'Nudge selected nodes (Shift = 10px steps)',
    altArrows: 'Alt + arrow keys',
    altArrowsDesc: 'Move focus between nodes (parent/child/sibling)',
    collapse: 'Collapse/Expand',
    collapseDesc: 'Toolbar or context menu',
    delete: 'Delete / Backspace',
    deleteDesc: 'Delete selected nodes',
  },
  shortcuts: {
    title: 'Keyboard shortcuts',
    subtitle: 'CladeForge shortcut reference',
    global: 'Global',
    canvas: 'Canvas',
    palette: 'Command palette',
    close: 'Close',
    searchPlaceholder: 'Search shortcuts…',
    noResults: 'No matching shortcuts',
  },
  legend: {
    title: 'Legend',
    toggle: 'Legend',
    toggleTitle: 'Canvas colour legend',
    mrca: 'Most recent common ancestor',
    selection: 'Selected node',
    dropTarget: 'Drop target',
    connectSource: 'Link source',
    transition: 'State transition (known ↔ known)',
    needsData: 'Needs data (endpoint unassigned — not an evolutionary change)',
    asr: 'ASR pie chart',
    event: 'Evolutionary event',
    era: 'Geological era band',
    stateMarker: 'Character state',
  },
  tour: {
    title: 'Welcome to CladeForge',
    step1Title: 'Canvas: start here',
    step1Desc: 'Drag nodes to move them, double-click to rename, scroll to zoom. Hovering a node shows its link port at the top-right.',
    step2Title: 'Inspector (right panel)',
    step2Desc: 'Select a node or link on the canvas, then edit its name, style, character states and other per-object properties here.',
    step3Title: 'Module panels (left)',
    step3Desc: 'Seven modules grouped into View / Content / Output: Style, Traits, Hypotheses, Reconcile (gene-tree DTL), Time, Analysis and Export.',
    step4Title: 'Command palette (⌘K)',
    step4Desc: 'Press ⌘K to search and run any action — re-layout, reroot, analysis and export all live here.',
    next: 'Next',
    skip: 'Skip',
    done: 'Get started',
    dismissedHint: 'Reopen via Help → Beginner Tour (or search “tour” in ⌘K).',
  },
  confirm: {
    deleteManyTitle: 'Confirm deletion',
    deleteManyMessage: (n: number, tips: number, pct: number) => `This will delete ${n} nodes (${tips} tips, ${pct}% of sampling). It can be undone. Continue?`,
    deleteManyConfirm: 'Delete',
    dontAskAgain: "Don't ask again this session",
    cancel: 'Cancel',
    rerootTitle: 'Confirm reroot',
    rerootMessage: 'Rerooting rearranges the whole topology and layout, and may change manual positions. Continue?',
    rerootConfirm: 'Reroot',
    rerootHasBranchLength: 'This tree has branch lengths; they will be preserved after rerooting.',
    rerootNoBranchLength: 'This tree has no branch lengths.',
    rerootAffectsChars: (n: number) => `Rerooting will affect ancestral-state annotations on ${n} internal node(s).`,
    deleteActiveLayerTitle: 'Delete active hypothesis layer?',
    deleteActiveLayerMessage: (current: string, next: string) => `The active hypothesis is “${current}”; after deletion it switches to “${next}”. Continue?`,
    deleteActiveLayerConfirm: 'Delete',
  },
  importMulti: {
    title: 'File contains multiple trees',
    hint: 'This file contains {n} trees. Choose which to import, or import all as separate tabs.',
    tips: 'tips',
    depth: 'depth',
    importSelected: 'Import selected',
    importAll: 'Import all',
    cancel: 'Cancel',
    consensus: 'Build consensus tree',
    consensusMethod: 'Consensus method',
    strict: 'Strict consensus',
    majorityRule: '50% majority rule',
  },
  nav: {
    groupContent: 'Content',
    groupView: 'View',
    groupOut: 'Output',
    traits: 'Traits',
    traitsHint: 'Character definitions & colour mapping',
    layers: 'Hypotheses',
    layersHint: 'Competing hypothesis layers',
    recon: 'Reconcile',
    reconHint: 'Gene-tree / species-tree DTL reconciliation',
    time: 'Time',
    timeHint: 'Time calibration & environmental context',
    style: 'Style',
    styleHint: 'Layout & global styling',
    analysis: 'Analysis',
    analysisHint: 'Inference & analysis',
    export: 'Export',
    exportHint: 'Export files',
  },
  recon: {
    section: 'Reconciliation (DTL)',
    geneTrees: 'Gene trees',
    importFile: 'Import gene tree from file',
    importTab: 'Import from open tab',
    rename: 'Rename',
    remove: 'Remove gene tree',
    empty: 'No gene trees yet. Import one and match its tips to the current species tree by name for DTL reconciliation.',
    activeGene: 'Active gene tree',
    mappedCount: 'Resolved internal nodes',
    cntSpeciation: 'Speciations σ',
    cntDuplication: 'Duplications δ',
    cntTransfer: 'Transfers τ',
    cntLosses: 'Losses λ',
    validation: 'Consistency check',
    noIssues: 'No inconsistencies',
    issuesTitle: 'Issues (click to locate)',
    suggestLca: 'Suggest via LCA',
    clearAssumptions: 'Clear assumptions',
    costs: 'Costs (δ / τ / λ)',
    costDup: 'Duplication δ',
    costTransfer: 'Transfer τ',
    costLoss: 'Loss λ',
    dpRun: 'Compute optimum (DP)',
    dpApply: 'Apply optimum as assumptions',
    dpCurrent: 'Current scenario cost',
    dpOptimal: 'DP optimal cost',
    // The absolute event / loss totals of this DP are not comparable with
    // RAINIEFF / RaGTeP / Treerecon output — the panel says so wherever such a
    // number is quoted.
    dpComparability: 'Scope statement: this is a minimum-cost parsimony reconciliation, not a likelihood, and three deliberate choices make its absolute event/loss totals LOWER than RAINIEFF / RaGTeP / Treerecon: the gene-tree root may be placed freely without paying for the arrival of the family (price it below), lineages passing a species junction without entering a sibling branch are not charged per junction, and unconstrained species clades pay no speculative losses. Quote these as "events under this model", never as counts interchangeable with another program.',
    dpInvariant: 'Both figures re-price the same scenario under the same costs, so they are comparable: equality means the current hypothesis is already optimal for this cost vector.',
    dpFreeRoot: (cost: number) => `The gene root sits inside the species tree (free root): this cost excludes the family-arrival fee (rootTransferCost = ${cost}).`,
    dpAmbiguousNodes: (n: number) => `${n} gene node(s) have other event classes at exactly the same cost (the classic duplication/speciation non-identifiability, plus mirrored transfer directions): one is shown under the documented priority duplication > speciation > transfer, but it is not the only optimum.`,
    dpAmbiguousLabels: (n: number) => `${n} tip label(s) collide after normalisation (case/underscores) and were left unmapped, so they take no part in the reconciliation.`,
    lossSplit: (internal: number, tips: number) => `losses = ${internal} on internal branches + ${tips} on gene-tip branches (tip-branch losses are now counted)`,
    costsRejected: 'Cost settings partially rejected',
    dpNoBinary: 'The solver needs a binary gene tree',
    severityError: 'Error',
    severityWarning: 'Note',
    enterView: 'Enter reconciliation view',
    exitView: 'Back to standard view',
    viewStandard: 'Standard view',
    viewRecon: 'Reconciliation view',
  },
  reconInspector: {
    title: 'DTL assumption',
    mapTo: 'Map to species node',
    event: 'Event type',
    evSpeciation: 'Speciation σ',
    evDuplication: 'Duplication δ',
    evTransfer: 'Transfer τ',
    evClear: 'Clear event',
    losses: 'Losses (incoming branch)',
    emptyHint: 'Click a node in the right gene pane to inspect/edit its DTL assumption; Alt+click a species node in the left pane to set the mapping of the selected gene node.',
    tipHint: 'Tips only carry a mapping, never an event.',
    geneTreeSection: 'Gene tree info',
    tipCount: 'Tip count',
  },
  exportGroup: {
    vector: 'Vector',
    raster: 'Raster',
    data: 'Data files',
    report: 'Reports',
  },
  nexusExport: {
    title: 'NEXUS export options',
    includeCharacters: 'Include character matrix (CHARACTERS block)',
    includeHypothesis: 'Include hypothesis layers (ASSUMPTIONS block)',
    includeMrBayes: 'Generate MrBayes block',
    includeBeast: 'Generate BEAST block',
    confirm: 'Export',
    cancel: 'Cancel',
  },
  inspector: {
    empty: 'Nothing selected',
    emptyHint: 'Click a node or link on the canvas to edit its individual properties here. For global styles use the “Style” module on the left.',
    searchPlaceholder: 'Search properties…',
    noResults: 'No matching properties',
    noResultsHint: 'Nothing found. Global defaults live in the “Style” module on the left.',
    advanced: 'Advanced',
    inherited: 'Inherits global default',
    overridden: 'Overrides global default',
    restoreDefault: 'Reset to default',
    restoreDefaultTitle: 'Clear this object’s style overrides and restore global defaults',
  },
  tabs: {
    newTab: 'New tab',
    close: 'Close tab',
    untitled: 'Untitled',
    closeConfirmTitle: 'Close tab?',
    closeConfirmMessage: (name: string) => `Tab "${name}" has unsaved changes that cannot be recovered. Close anyway?`,
  },
  cmd: {
    placeholder: 'Type a command or English alias…',
    none: 'No matching commands',
    newTab: 'New tab',
    open: 'Open project…',
    save: 'Save project',
    importTree: 'Import tree…',
    exportSvg: 'Export SVG',
    exportPng: 'Export PNG',
    exportPdf: 'Export PDF',
    exportNewick: 'Export Newick',
    exportNexus: 'Export Nexus',
    exportNarrative: 'Export narrative report',
    exportHypothesis: 'Export hypothesis JSON',
    undo: 'Undo',
    redo: 'Redo',
    fit: 'Fit to window',
    relayout: 'Re-layout',
    ladderizeAsc: 'Ladderize (ascending)',
    ladderizeDesc: 'Ladderize (descending)',
    rerootHere: 'Reroot at selected node',
    rerootMidpoint: 'Midpoint reroot',
    rerootOutgroup: 'Root with the selected clade as outgroup',
    rerootOutgroupCount: (n: number) => `Root with selected outgroup (${n} nodes selected)`,
    addBinary: 'Add binary split',
    toggleCollapse: 'Collapse/expand selection',
    runAsr: 'Mk likelihood reconstruction',
    matrix: 'Open character matrix',
    analysis: 'Inference assistant',
    search: 'Search nodes',
    guide: 'Beginner tour',
    extractSubtree: 'Extract subtree to new tab',
  },
  addDialog: {
    title: 'Add a polytomy',
    countLabel: 'Number of children',
    polytomyType: 'Polytomy type',
    hardPolytomy: 'Hard polytomy (simultaneous split)',
    softPolytomy: 'Soft polytomy (unresolved)',
    cancel: 'Cancel',
    confirm: 'Add',
  },
  context: {
    deleteEdge: 'Delete link',
    addBinary: 'Add binary split',
    addTernary: 'Add ternary split',
    addMulti: 'Add polytomy…',
    addSibling: 'Add sibling node',
    insertParent: 'Insert parent node',
    reroot: 'Reroot at this node',
    outgroupReroot: 'Set as outgroup & reroot',
    // The item must be reachable from a single selected node too, and its
    // label has to say how many nodes form the outgroup.
    outgroupRerootCount: (n: number) => `Root with the selected ${n} node(s) as outgroup`,
    expandSubtree: 'Expand subtree',
    collapseSubtree: 'Collapse subtree',
    resetPosition: 'Reset position',
    deleteNode: 'Delete node',
    fit: 'Fit to window',
  },
  dash: {
    solid: 'Solid',
    dashed: 'Dashed',
    dotted: 'Dotted',
  },
  branchShape: {
    label: 'Branch shape',
    line: 'Thin line',
    rectangular: 'Thick bar',
    rounded: 'Rounded bar',
  },
  node: {
    section: 'Node',
    name: 'Name',
    branchLength: 'Branch length',
    support: 'Support',
    age: 'Age',
    timeConstraintSection: 'Time constraint',
    calibrationMin: 'Min age',
    calibrationMax: 'Max age',
    noCalibration: 'No time calibration for this node.',
    addCalibration: 'Add calibration',
    styleSection: 'Node style',
    shape: 'Shape',
    shapeCircle: 'Circle',
    shapeSquare: 'Square',
    shapeDiamond: 'Diamond',
    shapeNone: 'None',
    size: 'Size',
    fill: 'Fill',
    stroke: 'Stroke',
    strokeWidth: 'Stroke width',
    labelSection: 'Label',
    showLabel: 'Show label',
    labelColor: 'Label colour',
    fontSize: 'Font size',
    fontWeight: 'Font weight',
    rotation: 'Rotation',
    italic: 'Italic',
    bold: 'Bold',
    labelPosition: 'Label position',
    labelOffsetX: 'Label X offset',
    labelOffsetY: 'Label Y offset',
    branchSection: 'Incoming branch style',
    branchShape: 'Branch shape',
    color: 'Colour',
    width: 'Width',
    dash: 'Dash',
    expand: 'Expand',
    collapse: 'Collapse',
    resetPosition: 'Reset position',
    delete: 'Delete',
    portTitle: 'Drag to another node to create a custom link',
  },
  edge: {
    section: 'Custom link',
    label: 'Label',
    color: 'Colour',
    width: 'Width',
    dash: 'Dash',
    arrow: 'Arrow',
    curvature: 'Curvature',
    delete: 'Delete link',
  },
  multi: {
    section: 'Multi-selection',
    applyToAll: 'Apply to selected',
    fill: 'Fill',
    stroke: 'Stroke',
    nodeSize: 'Node size',
    labelColor: 'Label colour',
    fontSize: 'Font size',
    branchColor: 'Branch colour',
    showLabel: 'Show labels',
    hideLabel: 'Hide labels',
    deleteSelected: 'Delete selected',
  },
  doc: {
    layoutSection: 'Layout & canvas',
    hGap: 'Level gap',
    vGap: 'Sibling gap',
    background: 'Canvas background',
    defaultsSection: 'Default styles',
    defaultBranchColor: 'Default branch colour',
    defaultEdgeColor: 'Default link colour',
    hintSection: 'Gesture hints',
  },
  fontWeightOpts: {
    light: 'Light (300)',
    normal: 'Regular (400)',
    medium: 'Medium (500)',
    semibold: 'Semibold (600)',
    bold: 'Bold (700)',
    black: 'Black (900)',
  },
  layoutPanel: {
    title: 'Global layout',
    presetSection: 'Style presets',
    layoutSection: 'Tree layout',
    type: 'Layout',
    orientation: 'Orientation',
    spacingSection: 'Spacing',
    branchGap: 'Sibling gap',
    levelGap: 'Level gap',
    branchSection: 'Branch style',
    branchShape: 'Branch shape',
    branchWidth: 'Branch width',
    branchColor: 'Branch colour',
    gradientSection: 'Colour gradient',
    gradientEnable: 'Enable gradient',
    gradientFrom: 'Root colour',
    gradientTo: 'Tip colour',
    gradientHint: 'Root→tip gradient for branches without an override.',
    fontSection: 'Font & labels',
    fontSize: 'Font size',
    fontWeight: 'Font weight',
    rotation: 'Rotation',
    italic: 'Italic',
    bold: 'Bold',
    showLabel: 'Show labels',
    labelColor: 'Label colour',
    canvasSection: 'Canvas',
    background: 'Canvas background',
    edgeSection: 'Default link',
    edgeColor: 'Link colour',
    timeSection: 'Time axis',
    timeUnit: 'Time unit',
    // The unit is a closed list, not free text: the ICS era bands and the axis
    // are hard-wired to Ma, so a value like "ka" would shift the whole colour
    // band by 10³ without complaint. Anything but Ma turns the geological
    // overlay off instead of lying.
    timeUnitMa: 'Ma (megayears — the unit the geological bands use)',
    timeUnitKa: 'ka (kayears)',
    timeUnitGa: 'Ga (gigayears)',
    timeUnitMyr: 'Myr (megayears, same scale as Ma)',
    timeUnitYr: 'yr (years)',
    timeUnitOther: 'other / custom',
    timeUnitHint: (unit: string) => `No conversion is applied: node ages and event intervals are still read as the numbers you typed, only the label says “${unit}”. Convert your data beforehand if you need another scale.`,
    timeUnitBlocksEras: (unit: string) => `The ICS eon/period bands are defined in Ma (layout/timescale.ts) and the current unit “${unit}” is not Ma ⇒ the bands are switched off rather than drawn 1000× out of place.`,
    showEras: 'Show geological eras',
    circularIgnoresAges: 'The circular layout orders radii by topological depth only: it never reads node ages, so the time axis, the eon/period bands and the environmental-event ribbon all disappear (the data is untouched — it is simply not consumed).',
    phylogramMissingLengths: (n: number, total: number) => `${n} of ${total} branches have no usable length: they are drawn at zero length on their topological depth and marked grey dashed, because their horizontal distance means nothing — the scale bar describes only the branches that carry a length.`,
    branchLengthUnknownLegend: 'grey dashed branch = no recorded length (not a zero length)',
    estimateAges: 'Estimate ages from topology',
    agesEstimated: 'Ages estimated from topology; fine-tune them on the time axis',
    agesAreEstimated: 'Some ages in this tree are topology-derived (not fossil or calibration evidence); review them before using the tree for analysis or publication.',
    timeHint: 'Geological time chart: nodes are placed by entered ages; set each node on the right.',
    timeNotCalibrated: 'This is a purely topological tree with no time data. Time axis and environmental events are unavailable.',
    timeNotCalibratedHint: 'Set node ages or add calibration points first, or click "Estimate ages from topology" to generate relative time.',
    timeCalibrated: 'Time data detected; time-axis features are available.',
    // Shown when the tree has time data but the layout is not time-calibrated.
    timeDataButWrongLayout: (layoutName: string) => `Time data is ready, but the current layout is “${layoutName}”. Switch to “Geological time chart” to show the time axis and environmental events.`,
    switchToTimeChart: 'Switch to geological time chart',
    eraLevelLabel: 'Display level',
    eraLevelEon: 'Eons only',
    eraLevelPeriod: 'Periods only',
    eraLevelBoth: 'Eons and periods',
    // Shown when time-calibrated layout is active but some nodes lack ages.
    missingAgesWarning: (n: number) => `${n} node(s) have no age set and will be placed at present (0)`,
    missingAgesListPrefix: 'Nodes missing ages: ',
    missingAgesMore: (n: number) => `${n} more`,
    // Clarification that calibration points don't affect the layout.
    calibrationHint: 'Calibration points are exported with NEXUS only; they do not automatically estimate node ages.',
    envSection: 'Environmental events',
    envAdd: '+ Add environmental event',
    envFrom: 'From',
    envTo: 'To',
    envEmpty: 'No environmental events yet (climate / drift / mass extinction…).',
    applyHint: 'Global settings; individual objects can override in the right panel.',
    calibrationSection: 'Calibration points',
    calibrationAdd: '+ Add calibration point',
    calibrationNode: 'Node',
    calibrationMin: 'Min age',
    calibrationMax: 'Max age',
    calibrationEmpty: 'No calibration points yet. Add at least one to enable time calibration.',
    supportSection: 'Support threshold',
    supportThreshold: 'Support threshold (0–100)',
    // The control drives both the canvas and the exported figure, and a stored
    // 0–1 posterior is normalised to a percentage before the comparison, so a
    // Bayesian tree is not entirely faded out.
    supportThresholdHint: 'Branches below the threshold are faded (dashed + lighter) on the canvas and in the exported figure. Support is compared on a 0–100 scale; a stored 0–1 posterior probability is converted first.',
    supportThresholdNoData: 'This tree carries no support values, so the threshold changes nothing.',
  },
  character: {
    section: 'Characters & states',
    colorBy: 'Colour by',
    colorByNone: 'None (node style)',
    showTransitions: 'Show state transitions',
    list: 'Characters',
    empty: 'No characters yet — create one below.',
    add: 'New character',
    openMatrix: 'Character matrix…',
    analysisMenu: 'Analysis ▾',
    edit: 'Edit',
    name: 'Name',
    type: 'Type',
    typeDiscrete: 'Discrete',
    typeContinuous: 'Continuous',
    states: 'States',
    addState: '+ Add state',
    stateLabel: 'State name',
    lowColor: 'Low value colour',
    highColor: 'High value colour',
    deleteCharacter: 'Delete character',
    stepMatrix: 'Cost matrix (Sankoff)',
    stepMatrixHint: 'Row→column is the “from→to” transition cost; affects parsimony suggestions and consistency checks.',
    resetWeights: 'Reset to equal weights',
    analysis: 'Inference assistant…',
    asr: 'Ancestral reconstruction',
    runAsr: 'Mk likelihood reconstruction',
    clearAsr: 'Clear',
    asrHint: 'Computes state probability distributions (pie charts) for internal nodes under the equal-rates Mk model.',
    done: 'Done',
  },
  matrix: {
    title: 'Character matrix',
    taxon: 'Taxon (tip)',
    close: 'Close',
    unassigned: '—',
    empty: 'Create at least one character in the left panel first.',
    hint: 'Only leaves are listed (observed states); set ancestral-state hypotheses for internal nodes in the right panel.',
  },
  nodeChar: {
    section: 'Character states',
    tipHint: 'Leaf: observed state.',
    internalHint: 'Internal node: your ancestral-state hypothesis.',
    unassigned: '(unset)',
    missing: 'Missing (?)',
    notApplicable: 'Not applicable (-)',
    valuePlaceholder: 'Value',
    noCharacters: 'No characters defined yet; create one under “Characters & states” on the left.',
    evidence: 'Evidence',
    suggest: 'Parsimony suggestion',
    accept: 'Accept',
    ambiguous: 'Multiple equally optimal resolutions exist',
  },
  event: {
    section: 'Evolutionary events',
    showEvents: 'Show events',
    add: '+ Add event',
    type: 'Type',
    target: 'Anchor',
    targetNode: 'Node',
    targetBranch: 'Branch (incoming)',
    label: 'Title',
    labelPlaceholder: '(defaults to type name)',
    note: 'Description',
    triggers: 'Triggers (causal chain)',
    triggersNone: 'No other events to link yet',
    delete: 'Delete event',
    empty: 'No events on this node/branch yet.',
  },
  confidence: {
    label: 'Confidence',
    none: '(unset)',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    support: 'Supporting evidence',
    against: 'Contradicting evidence',
  },
  analysis: {
    title: 'Inference assistant',
    character: 'Character',
    parsimonySection: 'Parsimony (ancestral-state suggestions)',
    cost: 'Minimum cost / changes',
    fill: 'Generate parsimony suggestions',
    fillHint: 'Generates a suggested state for each internal node (non-destructive); accept them individually in the right panel.',
    signalSection: 'Phylogenetic signal (CI/RI)',
    steps: 'Changes s',
    minSteps: 'Minimum steps m',
    maxSteps: 'Maximum steps g',
    signalHint: 'CI = m/s, RI = (g−s)/(g−m). Closer to 1 means the character fits the topology; low values hint at homoplasy (convergence/parallelism) worth investigating. Both are only defined for equally weighted (unweighted) changes.',
    signalNone: 'Needs ≥3 scored tips and ≥2 states.',
    signalWeighted: 'This character carries a Sankoff step matrix: CI/RI count STEPS (m = states − 1, g = tips − modal count), which a weighted score makes meaningless, so none is reported.',
    signalMissingCodes: (n: number) => `${n} tip value(s) are missing-data codes (? / -) or deleted states and are excluded from m, g and s.`,
    consistencySection: 'Consistency checks',
    consistencyNone: 'No obvious issues found.',
    consistencyAmbiguous: 'Ambiguous reconstruction',
    consistencyHomoplasy: 'Homoplasy',
    consistencyMissing: 'Missing-data impact',
    consistencyMismatch: 'Local inconsistency',
    consistencyExcess: 'Excess changes',
    correlationSection: 'Character correlation',
    // The metric is the Jaccard overlap of the two characters' MP change-branch
    // sets, not a Phi coefficient. The overlap is descriptive; significance only
    // appears after the tree-constrained permutation test has actually been run.
    correlationNone: 'No character pairs reach a Jaccard overlap ≥ 0.5 (needs ≥2 discrete characters, each with ≥2 change branches).',
    correlationType: 'Jaccard overlap ratio',
    correlationSample: (n: number) => `n = ${n}`,
    correlationShared: (shared: number, a: number, b: number) => `${shared} shared change branches (A: ${a} / B: ${b})`,
    correlationExpected: (v: number) => `independent expectation ≈ ${v.toFixed(2)} branches (|A|·|B|/|N| over ALL branches)`,
    correlationDescriptive: 'The overlap ratio is descriptive: high overlap marks a co-change worth investigating — it is neither significance nor causation.',
    correlationRunTest: 'Run tree-constrained permutation test',
    correlationRerunTest: 'Re-run permutation test',
    correlationTesting: 'Running permutation test…',
    correlationTestHint: 'The test shuffles character B\u2019s states over the tips scored for B (keeping its state frequencies and missing-data pattern), recomputes B\u2019s parsimony change-branch set on the same topology and step matrix, and compares the same Jaccard statistic: p = (1 + replicates ≥ observed) / (replicates + 1).',
    correlationTestMethod: (method: string) => `Method: ${method}`,
    correlationPValue: 'raw permutation p',
    correlationPSummary: (p: number, perms: number, resolution: number) =>
      `p ${p <= resolution ? '<' : '='} ${p <= resolution ? resolution.toFixed(4) : p.toFixed(4)} (${perms} permutations)`,
    correlationNullMean: (v: number) => `null mean ${v.toFixed(3)}`,
    correlationSignificant: (n: number) =>
      `${n} pair(s) significant after Holm–Bonferroni correction (α = 0.05)`,
    correlationNoSignificance: 'No test run ⇒ only the overlap ratio is shown, with no significant / not-significant verdict.',
    correlationMultiTest: (pairs: number) =>
      `${pairs} p-values in this family, Holm–Bonferroni step-down adjusted; only the adjusted values are read against 0.05 (an unadjusted p is not a 0.05 test statistic once more than one pair is on screen)`,
    // Multiplicity control, and the inference is kept separate from the
    // descriptive ≥0.5 gate, so the UI has to name both.
    correlationPAdjusted: 'Holm–Bonferroni adjusted p',
    correlationVerdictYes: 'significant after correction (≤ 0.05)',
    correlationVerdictNo: 'not significant after correction (> 0.05)',
    correlationAllTestedTitle: 'All results in the family (including pairs under the 0.5 descriptive gate)',
    correlationSkippedPairs: (n: number) =>
      `${n} further pair(s) were left out of the family (permutation cost cap): unadjusted, no verdict`,
    correlationGateNote:
      'Every pair whose two change-branch sets hold ≥2 branches enters the test family, and all p-values in the family are corrected together before significance is judged',
    correlationNotTestable: (why: string) => `This pair cannot be tested (${why}); descriptive overlap only`,
    correlationNotTestableWhy: 'too few usable permutations (tree too large or <3 tips scored for both)',
    close: 'Close',
    needCharacter: 'Create and select a discrete character on the left first.',
    treeSummarySection: 'Tree summary',
    tipCount: 'Tips',
    internalCount: 'Internal nodes',
    resolution: 'Resolution (binary ratio)',
    avgBranchLength: 'Mean branch length',
    totalBranchLength: 'Total branch length',
    treeHeight: 'Tree height (root-to-tip)',
    treeHeightUnitBranch: 'unit: branch lengths (recorded in this tree)',
    treeHeightUnitEdges: 'unit: edges (no branch lengths at all, so topological depth)',
    sackinIndex: 'Sackin index',
    collessIndex: 'Colless index',
    // Colless is defined for rooted BINARY trees; what the code emits for
    // a tree with polytomies is the max−min variant, un-normalised.
    collessBinaryOnly: (n: number) => `${n} internal node(s) are non-binary: this is the max−min multifurcation variant, not normalised by n, and not comparable with a binary tree's Colless value.`,
    branchLengthCoverage: (have: number, missing: number) => `${have} branch(es) carry a length, ${missing} do not; unset and non-finite values count as 0 in the total, while a recorded 0 (synchronous divergence) is real data.`,
    continuousSection: 'Continuous characters',
    blombergK: "Blomberg's K",
    // K is a point estimate here. Without the trait-shuffling / BM-simulation
    // test it licenses no evolutionary verdict, so the wording is a reading aid
    // and never "conservative" / "over-dispersed".
    blombergKHint: "K is a point estimate relative to Brownian motion (BM = 1): K > 1 means more clustered than BM, K < 1 more dispersed. This program runs no permutation or simulation test, so no evolutionary conclusion is drawn from it.",
    blombergKNoTest: 'No significance test: the gap between K and 1 may lie entirely inside the random range a permutation test would return.',
    blombergKScale: (imputed: number, total: number) =>
      imputed === 0
        ? `branch-length coverage: ${total}/${total} branches use the supplied lengths`
        : `branch-length coverage: only ${total - imputed}/${total} branches have a length, the rest are imputed as 1 ⇒ this is the TOPOLOGICAL (cladogram-scale) K, not a time-scaled one`,
    continuousNone: 'Needs at least one scored continuous character.',
    continuousBlockedReason: (why: string) => `No K reported: ${why}`,
    asrModelSection: 'ASR model settings',
    asrModel: 'Rate model',
    asrModelER: 'ER (equal rates)',
    asrThreshold: 'Only show states with p > threshold',
    asrThresholdHint: (t: number) =>
      `Pie wedges with posterior < ${t.toFixed(2)} are not drawn; when one state reaches ${(1 - t).toFixed(2)} (every other state is then under the cut-off) the pie is filled solid with that state. The renderer reads this threshold — it is display-only and never enters the likelihood.`,
    asrRun: 'Run ASR',
    asrResultSummary: 'Result summary',
    asrNoWarnings: 'No degradation warnings',
    asrWarningCount: (n: number) => `${n} degradation warning class(es)`,
    asrWarningList: (kind: string, n: number) => `${kind}: ${n} node(s)`,
    // The four degradation classes are distinct statements — an unset
    // length is not a recorded zero.
    asrWarnUnset: 'no branch length recorded (imputed as 1)',
    asrWarnZero: 'branch length recorded as 0 (synchronous divergence, used as 0)',
    asrWarnNegative: 'negative branch length (invalid, imputed as 1)',
    asrWarnInvalid: 'non-finite branch length NaN/∞ (invalid, imputed as 1)',
    asrWarnCollapse: 'posterior collapse (all −∞, fell back to uniform)',
    asrModelErOnly: 'Only the ER (equal-rates) Mk model is implemented: the closed-form transition matrix holds for ER alone, so SYM/ARD are not offered.',
  },
  layer: {
    section: 'Hypothesis layers',
    current: 'Active hypothesis',
    name: 'Name',
    addBlank: 'New',
    duplicate: 'Duplicate',
    remove: 'Delete',
    copySuffix: 'copy',
    hint: 'Multiple hypotheses are kept independently; tip observations are shared.',
  },
  characterExtra: {
    symmetric: 'Symmetric mode',
    symmetricHint: 'Edit the upper triangle only; the lower mirrors automatically.',
    missingData: 'Missing (?)',
    notApplicable: 'Not applicable (-)',
    // A stored value that is neither a declared state nor a missing-data code —
    // kept visible but not selectable.
    staleValue: (id: string) => `stale value ${id} (not a state of this character)`,
  },
  group: {
    hypothesisData: 'Hypotheses & data',
    layoutStyle: 'Layout & style',
  },
  analysisMenu: {
    label: 'Analysis',
    matrix: 'Character matrix…',
    inference: 'Inference assistant…',
    asr: 'Mk likelihood reconstruction',
    clearAsr: 'Clear reconstruction',
  },
  canvasControls: {
    zoomIn: '＋',
    zoomOut: '－',
    actualSize: '1:1',
    fit: 'Fit',
    relayout: 'Tidy',
    zoomInTitle: 'Zoom in',
    zoomOutTitle: 'Zoom out',
    actualSizeTitle: 'Actual size (100%)',
    fitTitle: 'Fit to window',
    // fitView clamps at MIN_SCALE, so "fit" silently fails to show the
    // whole tree on very tall layouts; the zoom readout says so.
    fitClampedTitle: 'The minimum zoom (10%) was reached: the tree still does not fit — increase the spacing or collapse subtrees',
    fitClamped: 'at minimum zoom',
    relayoutTitle: 'Clear manual positions and re-layout at fixed spacing',
  },
  panel: {
    resizeTitle: 'Drag to resize the panel',
    closeOverlay: 'Close panel',
  },
  section: {
    pin: 'Keep expanded',
    unpin: 'Unpin (collapsible)',
    items: 'items',
    unfavorite: 'Unfavorite',
    favorite: 'Favorite',
  },
  busy: {
    exportPdf: 'Exporting PDF…',
    exportPng: 'Exporting PNG…',
    exportSvg: 'Exporting SVG…',
  },
empty: {
title: 'Start building your phylogeny',
hint: 'Drop a .nwk / .nex / .tree file, press ⌘O / Ctrl+O to import, or use “+ Add children” in the left toolbar.',
loadSample: 'Load sample tree',
loadSampleTitle: 'Load a sample tree with characters and events to explore the app',
samplePickerTitle: 'Choose a sample project',
samplePickerHint: 'Examples covering archaea, bacteria, viruses, and animal/plant evolution — each with characters and events',
},
  notify: {
    openProjectFail: 'Failed to open project',
    saveProjectFail: 'Failed to save project',
    importFail: 'Failed to import tree',
    exportNewickFail: 'Failed to export Newick',
    exportNexusFail: 'Failed to export Nexus',
    exportSvgFail: 'Failed to export SVG',
    exportPngFail: 'Failed to export PNG',
    exportPdfFail: 'Failed to export PDF',
    exportNarrativeFail: 'Failed to export narrative report',
    exportHypothesisFail: 'Failed to export hypothesis JSON',
    projectSaved: 'Project saved',
    projectOpened: 'Project opened',
    treeImported: 'Tree imported',
    exported: 'Exported',
    saveCancelled: 'Save cancelled',
    undo: 'Undo',
    addRootFallback: 'No node selected — children will be added to the root',
    noBranchLength: 'This tree has no branch lengths; rendering matches the cladogram',
    needBranchLength: 'Midpoint rerooting requires branch lengths',
    needCalibration: 'Add at least one calibration point first',
    consensusBuilt: 'Consensus tree built',
    consensusFail: 'Could not build a consensus tree',
    // The reason comes from `buildConsensusTree`'s issue sink, so a failed
    // consensus is never an unexplained failure.
    consensusIssues: (reason: string) => `The consensus tree could not be built: ${reason}`,
    consensusPartial: (reason: string) => `Consensus tree built, with caveats: ${reason}`,
    // Outgroup rooting needs a selection, and can legitimately be a no-op.
    outgroupNeedsSelection: 'Select the outgroup nodes first (Shift+click to multi-select)',
    outgroupNoOp: 'Outgroup rooting impossible here: the selection is the root itself, or sits directly beneath the current root (that taxon is already the basal branch)',
    outgroupDone: (n: number) => `Re-rooted on the selected outgroup (${n} nodes, selection kept)`,
    // The cost writer rejects unusable values; the panel says so.
    costsRejected: (why: string) => `Costs were not fully applied: ${why}`,
    timeNotCalibrated: 'This tree has no time data. Set node ages or add calibration points first, or click "Estimate ages from topology" to generate relative time.',
    timeDataInconsistent: (n: number) => `Found ${n} time-data inconsistency issue(s); check node ages or calibration points`,
    // Toast shown when switching to time-calibrated layout with nodes missing ages.
    missingAgesToast: (n: number) => `${n} node(s) have no age set and will be placed at present (0)`,
  },
};

// --- locale-independent identity for a catalogue string ----------------------
//
// Collapsible sections persist their open / pinned / favourited state under a
// stable identifier, never a hash of the *rendered title*: a title hash changes
// every key when the language switches, silently resetting the whole layout, and
// two sections that share a title in different panels would fight over one key.
//
// Both dictionaries are structurally identical, so the dot-path of a value
// (`layoutPanel.timeSection`) is a stable, language-free identifier for it. Index
// every leaf of both locales once and hand that path out; call sites that use the
// same key twice (same title in two panels) must still pass an explicit `id`.
const titlePaths = new Map<string, string>();

function indexPath(value: unknown, path: string): void {
  if (typeof value === 'string') {
    if (!titlePaths.has(value)) titlePaths.set(value, path);
    return;
  }
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      indexPath(v, path ? `${path}.${k}` : k);
    }
  }
}
// `en` is typed against `zh`, so indexing either one is enough — but indexing
// both means a string that only ever appears in one locale still resolves.
indexPath(zh, '');
indexPath(en, '');

/** Language-independent identifier for a rendered UI string (falls back to a hash). */
export function titleKey(title: string): string {
  const path = titlePaths.get(title);
  if (path) return path;
  let h = 0;
  for (let i = 0; i < title.length; i += 1) h = ((h << 5) - h + title.charCodeAt(i)) | 0;
  return `raw:${Math.abs(h).toString(36)}`;
}

// --- active locale -----------------------------------------------------------
// `S` is re-assigned by setLanguage(). ES-module live bindings mean every
// importer sees the new dictionary immediately; the app additionally remounts
// on language change so memoised subtrees pick up the new strings too.

let currentLang: Language = 'zh';

/** The active string catalogue. Live binding — never cache across a language
 *  switch at module scope. */
export let S: Strings = zh;

export function setLanguage(lang: Language): void {
  currentLang = lang;
  S = lang === 'en' ? en : zh;
}

export function getLanguage(): Language {
  return currentLang;
}

/** Pick between a Chinese and an English literal at call time — used for the
 *  few display strings that live outside the catalogue (domain labels, era
 *  names, validation messages…). */
export function tr(zhText: string, enText: string): string {
  return currentLang === 'en' ? enText : zhText;
}

/** "已删除 {n} 个节点" undoable-delete toast. */
export function deletedCount(n: number): string {
  return currentLang === 'en' ? `Deleted ${n} node${n === 1 ? '' : 's'}` : `已删除 ${n} 个节点`;
}

/** "文件包含 {n} 棵树，已导入第 1 棵" notice for multi-tree Newick files. */
export function importedFirstOf(n: number): string {
  return currentLang === 'en' ? `File contains ${n} trees; imported the first one` : `文件包含 ${n} 棵树，已导入第 1 棵`;
}

/** "已选择 {n} 个节点" */
export function selectedCount(n: number): string {
  return currentLang === 'en' ? `${n} node${n === 1 ? '' : 's'} selected` : `已选择 ${n} 个节点`;
}

/** "已修复 {n} 处问题" repair summary shown after opening a project. */
export function repairedCount(n: number): string {
  return currentLang === 'en' ? `Project opened; auto-repaired ${n} data issue(s)` : `项目已打开，自动修复了 ${n} 处数据问题`;
}

/** Notice shown when workspace restore skipped one or more corrupt tabs. */
export function skippedTabs(n: number): string {
  return currentLang === 'en' ? `Workspace restored; skipped ${n} corrupted tab(s)` : `工作区恢复：跳过了 ${n} 个损坏的标签页`;
}

/** Compose a failure message with its cause. */
export function withReason(prefix: string, reason: string): string {
  return currentLang === 'en' ? `${prefix}: ${reason}` : `${prefix}：${reason}`;
}
