// Hypothesis output: a human-readable narrative report (Markdown) and a curated
// hypothesis JSON, both derived from the ACTIVE layer's live data. These are
// distinct from the full project save (projectIO): they surface the semantic
// layer — characters, ancestral-state hypotheses, transitions, events (with
// causal links and evidence) and environmental context — for sharing, papers
// or continued analysis elsewhere.

import type { Character, Confidence, Project, TreeNode } from '../model/types';
import type { ConsistencyIssue } from '../model/consistency';
import { detectTransitions, MISSING_STATE_CODES, stateLabel } from '../model/characters';
import { causalPairs, eventCode, eventDisplayLabel, eventTypeLabel, findEventType } from '../model/events';
import { checkConsistency } from '../model/consistency';
import { S, tr } from '../ui/strings';

/**
 * Confidence wording for the narrative / JSON hypothesis export.
 *
 * Resolved at CALL time, not import time: a module-level map would freeze the
 * language, so an English narrative could print "(confidence: 高)" — and this
 * text is a citable supplementary artefact. Reading `S.confidence` also keeps
 * the export in the same vocabulary as the UI: "High", spelled exactly the way
 * the interface spells it.
 */
function confLabel(c: Confidence): string {
  return S.confidence[c];
}

function nodeLabel(project: Project, id: string): string {
  return project.nodes[id]?.label || id;
}

function tips(project: Project): TreeNode[] {
  return Object.values(project.nodes).filter((n) => n.childrenIds.length === 0);
}

function internals(project: Project): TreeNode[] {
  return Object.values(project.nodes).filter((n) => n.childrenIds.length > 0);
}

// --- narrative (Markdown) ----------------------------------------------------

export function buildNarrative(project: Project): string {
  const L: string[] = [];
  const unit = project.layout.timeUnit ?? 'Ma';
  const active = project.layers.find((l) => l.id === project.activeLayerId);
  // Escape inline-Markdown metacharacters in user-supplied text so a label or
  // note containing *, _, `, [ or ] cannot break the report's formatting. Escape
  // raw HTML as well, not just the punctuation: a label like
  // `<img src=x onerror=…>` would otherwise reach the document verbatim, and this
  // file is the long-term archive of a reasoning session — an archive that
  // re-renders as active markup in the reader's viewer is not an archive.
  const md = (s: string | number): string =>
    String(s)
      .replace(/([\\`*_[\]])/g, '\\$1')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  const nl = (id: string): string => md(nodeLabel(project, id));

  L.push(tr(`# ${md(project.name)} — 演化假说叙事`, `# ${md(project.name)} — Evolutionary hypothesis narrative`), '');
  L.push(tr(`> 由 CladeForge 自动生成。分类单元 ${tips(project).length} 个，内部节点 ${internals(project).length} 个。`, `> Generated by CladeForge. ${tips(project).length} taxa, ${internals(project).length} internal nodes.`));
  if (project.layers.length) {
    L.push(tr(`> 当前假说层：${md(active?.name ?? '—')}（共 ${project.layers.length} 套）。`, `> Active hypothesis layer: ${md(active?.name ?? '—')} (${project.layers.length} total).`));
  }
  L.push('');

  if (project.characters.length) {
    L.push(tr('## 性状与状态演化', '## Character & state evolution'), '');
    for (const c of project.characters) {
      L.push(`### ${md(c.name)}`);
      const root = project.nodes[project.rootId];
      const rootState = root?.charStates?.[c.id];
      const rootMeta = root?.charMeta?.[c.id];
      if (rootState !== undefined) {
        let s = tr(`- 根节点（${nl(project.rootId)}）假设状态：**${md(stateLabel(c, rootState) ?? rootState)}**`, `- Root (${nl(project.rootId)}) hypothesised state: **${md(stateLabel(c, rootState) ?? rootState)}**`);
        if (rootMeta?.confidence) s += tr(`（置信度：${confLabel(rootMeta.confidence)}）`, ` (confidence: ${confLabel(rootMeta.confidence)})`);
        L.push(s);
        if (rootMeta?.support) L.push(tr(`  - 支持证据：${md(rootMeta.support)}`, `  - Supporting evidence: ${md(rootMeta.support)}`));
        if (rootMeta?.against) L.push(tr(`  - 反对证据：${md(rootMeta.against)}`, `  - Contradicting evidence: ${md(rootMeta.against)}`));
      } else {
        L.push(tr('- 根节点状态未设定。', '- Root state not set.'));
      }
      if (c.type === 'discrete') {
        // Only genuine state-to-state changes are counted. An endpoint that is
        // unassigned, or that carries a missing-data symbol the character never
        // declares ('?' / '-' as written by the matrix editor), is NOT an
        // evolutionary transition: listing "陆生 → ?" among the transitions and
        // counting it would inflate the total of a citable artefact. Such branches
        // are reported separately, uncounted.
        const declared = new Set(c.states.map((s) => s.id));
        // A value is a declared state only when it is a state id of THIS
        // character; continuous characters store numbers.
        const realTransition = (v: string | number): boolean =>
          typeof v === 'string' && declared.has(v);
        const all = detectTransitions(project, c);
        const real = all.filter((t) => realTransition(t.from) && realTransition(t.to));
        const pending = all.filter((t) => !realTransition(t.from) || !realTransition(t.to));
        /**
         * An uncounted endpoint is printed AS DATA — the literal missing code the
         * matrix editor wrote ('?' / '-'), an explicitly unset slot, or a stale
         * state id. `detectTransitions` normalises all three to "未知", which tells
         * a reader nothing about which branches merely need scoring; those branches
         * belong in the output as data rather than as transitions.
         */
        const endpoint = (id: string): string => {
          const raw = project.nodes[id]?.charStates?.[c.id];
          if (raw === undefined) return tr('未赋值', 'unset');
          if (typeof raw === 'string' && declared.has(raw)) return stateLabel(c, raw) ?? raw;
          if (typeof raw === 'string' && MISSING_STATE_CODES.includes(raw)) return raw;
          return tr(`残留值 ${raw}`, `stale value ${raw}`);
        };
        if (real.length) {
          L.push(tr(`- 状态转变（${real.length} 处）：`, `- State transitions (${real.length}):`));
          for (const t of real) {
            L.push(tr(`  - 分支「${nl(t.nodeId)}」：${md(t.fromLabel)} → ${md(t.toLabel)}`, `  - Branch “${nl(t.nodeId)}”: ${md(t.fromLabel)} → ${md(t.toLabel)}`));
          }
        } else {
          L.push(tr('- 未标注明确的状态转变。', '- No explicit state transitions annotated.'));
        }
        // Branches the transition finder could not report at all — BOTH endpoints
        // carry no observation, so there is no change to draw — but where one of
        // them holds an EXPLICIT missing code. That is scored data ("this tip is
        // missing"), not a transition, so the two must stay separate: it belongs in
        // the needs-data list below, not in the count above.
        const reported = new Set(all.map((t) => t.nodeId));
        const gapBranches: { parentId: string; nodeId: string }[] = [];
        for (const node of Object.values(project.nodes)) {
          if (!node.parentId || reported.has(node.id)) continue;
          const raws = [
            node.charStates?.[c.id],
            project.nodes[node.parentId]?.charStates?.[c.id],
          ];
          if (raws.some((v) => typeof v === 'string' && MISSING_STATE_CODES.includes(v))) {
            gapBranches.push({ parentId: node.parentId, nodeId: node.id });
          }
        }
        const uncounted = [...pending, ...gapBranches];
        if (uncounted.length) {
          L.push(
            tr(
              `- 另有 ${uncounted.length} 处分支的一端未赋值或使用缺失符号（? / -），不计入转变总数：`,
              `- ${uncounted.length} further branch(es) have an unassigned or missing-symbol ('?' / '-') endpoint and are NOT counted as transitions:`,
            ),
          );
          for (const t of uncounted.slice(0, 20)) {
            const pair = `${endpoint(t.parentId)} → ${endpoint(t.nodeId)}`;
            L.push(tr(`  - 分支「${nl(t.nodeId)}」：${md(pair)}（未计入）`, `  - Branch “${nl(t.nodeId)}”: ${md(pair)} (not counted)`));
          }
          if (uncounted.length > 20) L.push(tr(`  - …另有 ${uncounted.length - 20} 处`, `  - …and ${uncounted.length - 20} more`));
        }
        // All four consistency-check categories belong in the report: filtering to
        // `homoplasy` would make the self-check look more complete than it is.
        const issues = checkConsistency(project, c);
        const ORDER: ConsistencyIssue['kind'][] = ['local-mismatch', 'excess-changes', 'homoplasy', 'ambiguous'];
        for (const kind of ORDER) {
          for (const i of issues.filter((x) => x.kind === kind)) L.push(tr(`- 提示（${i.tag}）：${i.message}`, `- Note (${i.tag}): ${i.message}`));
        }
        for (const i of issues.filter((x) => !ORDER.includes(x.kind))) {
          L.push(tr(`- 提示（${i.tag}）：${i.message}`, `- Note (${i.tag}): ${i.message}`));
        }
      }
      L.push('');
    }
  }

  if (project.events.length) {
    L.push(tr('## 演化事件', '## Evolutionary events'), '');
    for (const e of project.events) {
      const t = findEventType(e.typeId);
      const where =
        e.target === 'branch'
          ? tr(`分支「${nl(e.nodeId)}」`, `branch “${nl(e.nodeId)}”`)
          : tr(`节点「${nl(e.nodeId)}」`, `node “${nl(e.nodeId)}”`);
      let s = tr(
        `- \`${eventCode(e)}\` **${md(t ? eventTypeLabel(t) : tr('事件', 'Event'))}**「${md(eventDisplayLabel(e))}」位于${where}`,
        `- \`${eventCode(e)}\` **${md(t ? eventTypeLabel(t) : tr('事件', 'Event'))}** — ${md(eventDisplayLabel(e))} on ${where}`,
      );
      if (e.confidence) s += tr(`（置信度：${confLabel(e.confidence)}）`, ` (confidence: ${confLabel(e.confidence)})`);
      L.push(s);
      if (e.note) L.push(tr(`  - 说明：${md(e.note)}`, `  - Note: ${md(e.note)}`));
      if (e.support) L.push(tr(`  - 支持证据：${md(e.support)}`, `  - Supporting evidence: ${md(e.support)}`));
      if (e.against) L.push(tr(`  - 反对证据：${md(e.against)}`, `  - Contradicting evidence: ${md(e.against)}`));
    }
    const pairs = causalPairs(project);
    if (pairs.length) {
      L.push('', tr('**因果链**：', '**Causal chains**:'));
      for (const p of pairs) {
        L.push(`- ${md(eventDisplayLabel(p.from))} → ${md(eventDisplayLabel(p.to))}`);
      }
    }
    L.push('');
  }

  if (project.environmentalEvents.length) {
    L.push(tr('## 环境背景', '## Environmental context'), '');
    for (const ev of project.environmentalEvents) {
      const range = ev.from === ev.to ? `${ev.from} ${unit}` : `${ev.from}–${ev.to} ${unit}`;
      L.push(`- **${md(ev.label)}**（${range}）`);
      if (ev.note) L.push(`  - ${md(ev.note)}`);
    }
    L.push('');
  }

  return L.join('\n');
}

// --- curated hypothesis JSON -------------------------------------------------

/**
 * States of one node, keyed by CHARACTER ID. Keying by character *name* would not
 * line an evidence block up with its column — `evidence` below is keyed by
 * character id — and two characters sharing a name (nothing stops that) would
 * overwrite each other silently. `characters[]` in the payload is the
 * id → name/state dictionary.
 */
function charStateMap(project: Project, node: TreeNode): Record<string, string | number> {
  const out: Record<string, string | number> = {};
  for (const c of project.characters) {
    const v = node.charStates?.[c.id];
    // Discrete values are the STATE id (decode with characters[].states); a
    // label is not a key, and two characters can legitimately reuse one.
    if (v !== undefined) out[c.id] = v;
  }
  return out;
}

/** Evidence for one node, restricted to characters that still exist. */
function charEvidence(
  project: Project,
  node: TreeNode,
): Record<string, { confidence?: string; support?: string; against?: string }> {
  const out: Record<string, { confidence?: string; support?: string; against?: string }> = {};
  const ids = new Set(project.characters.map((c) => c.id));
  for (const [cid, meta] of Object.entries(node.charMeta ?? {})) {
    // A character can be deleted without its per-node evidence being cleaned up;
    // exporting that as evidence for a non-existent trait is a lie, so orphan keys
    // are dropped here (and counted, for the caller).
    if (!ids.has(cid)) continue;
    out[cid] = meta;
  }
  return out;
}

export function buildHypothesisJSON(project: Project): string {
  const active = project.layers.find((l) => l.id === project.activeLayerId);
  const allTips = tips(project);
  const evidenceOf = (n: TreeNode) => charEvidence(project, n);
  const scored = (n: TreeNode) => n.charStates && Object.keys(n.charStates).length > 0;
  const data = {
    app: 'CladeForge',
    kind: 'hypothesis-export',
    // The archive's own schema version, independent of the app release: `states`
    // and `evidence` are both keyed by character id and every tip is listed.
    version: '0.1.0',
    name: project.name,
    generatedAt: new Date().toISOString(),
    timeUnit: project.layout.timeUnit ?? 'Ma',
    activeLayer: active?.name ?? null,
    layers: project.layers.map((l) => l.name),
    tipCount: allTips.length,
    /** id → label dictionary for the `states` maps above / below. */
    characters: project.characters.map((c: Character) => ({
      id: c.id,
      name: c.name,
      type: c.type,
      states: c.states.map((s) => ({ id: s.id, label: s.label, color: s.color })),
    })),
    // Every tip is listed, scored or not: filtering unscored taxa would make this
    // row count disagree with the NEXUS export's NTAX for the same project.
    taxonMatrix: allTips.map((n) => ({
      taxon: n.label || n.id,
      nodeId: n.id,
      states: charStateMap(project, n),
      evidence: evidenceOf(n),
    })),
    ancestralHypotheses: internals(project)
      .filter((n) => scored(n))
      .map((n) => ({
        node: n.label || n.id,
        nodeId: n.id,
        states: charStateMap(project, n),
        evidence: evidenceOf(n),
      })),
    events: project.events.map((e) => ({
      type: findEventType(e.typeId)?.labelEn ?? findEventType(e.typeId)?.label ?? e.typeId,
      label: e.label ?? null,
      position: e.target,
      at: nodeLabel(project, e.nodeId),
      confidence: e.confidence ?? null,
      support: e.support ?? null,
      against: e.against ?? null,
      triggers: e.triggers
        .map((id) => {
          const te = project.events.find((x) => x.id === id);
          return te ? eventDisplayLabel(te) : null;
        })
        .filter(Boolean),
    })),
    environmentalEvents: project.environmentalEvents.map((ev) => ({
      label: ev.label,
      from: ev.from,
      to: ev.to,
      note: ev.note ?? null,
    })),
  };
  return JSON.stringify(data, null, 2);
}
